#!/usr/bin/env python3
"""
Experiment: exp06c_lgbm_bin_sspace_elementwise_reduced_nestedcv_cv2 (M1)

Config
- model: LightGBM 
- task: binary classification
- feature_design: elementwise similarity 
- sspace: enabled (strain-space features)
- feature_selection: enabled (within CV folds)

- CV:
  - nested_cv: enabled
  - Outer split:
    - CV2 scheme: drug pair + strain held-out
      - five independent brute-force CV2 splits are generated by selecting test-strain subsets
      such that the induced test set size falls within predefined row-fraction bands
      - training excludes all rows containing any test strains or any drug pairs induced by test strains
      - cross-edge rows violating disjointness are dropped by construction
  - Inner split:
    - StratifiedGroupKFold, groups = Drug Pair
    - random search over 32 sampled hyperparameter configs
    - selection metric: mean validation accuracy across inner folds
  - Final fit: refit best model on full outer-train, evaluate once on outer-test

Data integrity note
All preprocessing (missing values, dtypes, column validation, etc.) is performed upstream in preprocessing 
notebooks/scripts. This script assumes the processed inputs are clean and consistent.

Class encoding
The binary target is encoded as {0,1} where 1 corresponds to synergy and is treated as the
positive class for F1 and ROC-AUC.
"""

import json
import itertools

import numpy as np
import pandas as pd
import lightgbm as lgb
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from sklearn.model_selection import StratifiedGroupKFold, GroupKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    precision_recall_fscore_support,
)

from halo.paths import CC_FEATURES, SS_FEATURES, PROCESSED, MODEL_RESULTS
from halo.mappers.feature_mapper import FeatureMapper
from halo.shared_utils.data_io import classify_interaction


# ==========================
# 1) Feature selection helper
# ==========================
def select_features_lgbm(
    X_train: pd.DataFrame,
    y_train: np.ndarray,
    feat_cols: list[str],
    corr_min: float = 0.01,
    keep_top_frac: float = 0.30,
) -> list[str]:
    """
    Feature selection performed using training data only.

    Steps
    1) drop zero-variance features
    2) keep features with |corr(feature, y)| >= corr_min
       fallback: keep all variance-filtered features if none pass
    3) rank by LightGBM feature_importances_ and keep top fraction
    """
    var_series = X_train.var()
    kept_after_var = [c for c in feat_cols if var_series[c] > 0.0]

    if len(kept_after_var) == 0:
        raise ValueError("No features remained after variance filtering.")

    kept_after_corr = []
    y_train_s = pd.Series(y_train, index=X_train.index)

    for col in kept_after_var:
        corr = X_train[col].corr(y_train_s)
        if corr is not None and np.isfinite(corr) and abs(corr) >= corr_min:
            kept_after_corr.append(col)

    if not kept_after_corr:
        kept_after_corr = kept_after_var.copy()

    fs_model = lgb.LGBMClassifier(
        objective="binary",
        n_estimators=2000,
        random_state=777,
        n_jobs=1,
        learning_rate=0.03,
        max_depth=3,
        num_leaves=15,
        min_data_in_leaf=200,
        feature_fraction=0.4,
        bagging_fraction=0.8,
        bagging_freq=1,
        lambda_l2=50.0,
        lambda_l1=0.0,
        max_bin=127,
        min_gain_to_split=0.05,
    )

    fs_model.fit(X_train[kept_after_corr], y_train)

    feat_imp = pd.Series(
        fs_model.feature_importances_,
        index=kept_after_corr,
    ).sort_values(ascending=False)

    n_keep = max(1, int(len(feat_imp) * keep_top_frac))
    selected_features = feat_imp.index[:n_keep].tolist()
    return selected_features


# ==========================
# 2) Brute-force CV2 split generator
# ==========================
def brute_force_cv2_split(
    df,
    strain_col,
    pair_col,
    min_frac,
    max_frac,
    lambda_penalty=1.0,
    top_k_print=5,
    verbose=True,
):
    """
    Original brute-force CV2 logic:
    - Select a test subset of strains
    - All pairs belonging to those strains become test
    - Train = rows not using test strains AND not using test pairs
    - Drops rows that conflict with disjointness
    Returns (train_idx, test_idx, info_dict)
    """

    S_all = df[strain_col].astype(str).values
    P_all = df[pair_col].astype(str).values
    strains_uni = sorted(np.unique(S_all).tolist())
    n_total = len(df)

    min_target = int(round(min_frac * n_total))
    max_target = int(round(max_frac * n_total))

    if verbose:
        print("=" * 72)
        print(
            f"Brute-force CV2: min_frac={min_frac:.2f}, max_frac={max_frac:.2f}, "
            f"target rows [{min_target}, {max_target}]"
        )

    def eval_subset(S_test_set):
        if not S_test_set:
            return 0, 0, n_total, set(), -np.inf

        mask_s = np.isin(S_all, list(S_test_set))
        P_test_set = set(P_all[mask_s])
        test_mask = mask_s & np.isin(P_all, list(P_test_set))
        train_mask = (~mask_s) & (~np.isin(P_all, list(P_test_set)))

        kept = int(test_mask.sum())
        train = int(train_mask.sum())
        dropped = n_total - (kept + train)
        score = kept - lambda_penalty * dropped
        return kept, train, dropped, P_test_set, score

    candidates = []
    for r in range(1, len(strains_uni) + 1):
        for subset in itertools.combinations(strains_uni, r):
            S_test = set(subset)
            kept, train, dropped, P_test, score = eval_subset(S_test)
            if min_target <= kept <= max_target:
                candidates.append(
                    dict(
                        S_test=S_test,
                        P_test=P_test,
                        kept=kept,
                        train=train,
                        dropped=dropped,
                        score=score,
                    )
                )

    if not candidates:
        if verbose:
            print("No valid CV2 split found within band. Returning all-train.")
        return (
            np.arange(n_total),
            np.array([], dtype=int),
            dict(
                reason="no_candidates",
                test_strains=set(),
                test_pairs=set(),
                kept_test_rows=0,
                kept_train_rows=n_total,
                dropped_rows=0,
                params=dict(min_frac=min_frac, max_frac=max_frac),
            ),
        )

    candidates.sort(key=lambda c: (c["dropped"], -c["kept"], -c["score"]))

    best = candidates[0]
    S_test_best = best["S_test"]
    P_test_best = best["P_test"]

    test_mask = np.isin(S_all, list(S_test_best)) & np.isin(P_all, list(P_test_best))
    train_mask = (~np.isin(S_all, list(S_test_best))) & (~np.isin(P_all, list(P_test_best)))

    te_idx = np.where(test_mask)[0]
    tr_idx = np.where(train_mask)[0]
    dropped_rows = n_total - (te_idx.size + tr_idx.size)

    info = dict(
        mode="bruteforce_strains_pairs",
        test_strains=set(S_test_best),
        test_pairs=set(P_test_best),
        kept_test_rows=int(te_idx.size),
        kept_train_rows=int(tr_idx.size),
        dropped_rows=int(dropped_rows),
        params=dict(min_frac=min_frac, max_frac=max_frac, lambda_penalty=lambda_penalty),
        top_candidates=candidates[:top_k_print],
    )

    if verbose:
        print(
            f"BEST: test strains={len(S_test_best)}, test pairs={len(P_test_best)}, "
            f"kept={te_idx.size}, dropped={dropped_rows}"
        )

    return tr_idx, te_idx, info


# ==========================
# 3) MAIN EXPERIMENT
# ==========================
def main():
    corr_min = 0.01
    keep_top_frac = 0.30

    cc_path = CC_FEATURES / "cc_features_concat_25x128.csv"
    ss_path = SS_FEATURES / "sspace.csv"
    combos_path = PROCESSED / "halo_training_dataset.csv"

    out_dir = MODEL_RESULTS / "exp06c_lgbm_bin_sspace_elementwise_reduced_nestedcv_cv2"
    out_dir.mkdir(parents=True, exist_ok=True)

    print("\n=== EXP06c ===\n")
    print("Output dir :", out_dir)

    # load full data and rebuild full elementwise feature table
    cc_df = pd.read_csv(cc_path).copy()
    ss_df = pd.read_csv(ss_path).copy()
    combinations_df = pd.read_csv(combos_path).copy()

    features_cc_s = cc_df.merge(ss_df, on="inchikey", how="inner", suffixes=("", "_s"))
    df = FeatureMapper().elementwise_similarity(combinations_df, features_cc_s)
    print("Full df shape:", df.shape)

    df = df[df["Interaction Type"].isin(["synergy", "antagonism"])].copy()
    print("\nAfter filtering to synergy/antagonism:", df.shape)
    print(df["Interaction Type"].value_counts())

    drop_cols = [
        "Drug A",
        "Drug B", 
        "Drug A Inchikey", 
        "Drug B Inchikey",
        "Strain", 
        "Specie", 
        "Bliss Score", 
        "Interaction Type",
        "Source", 
        "Drug Pair",
    ]

    feat_cols = [c for c in df.columns if c not in drop_cols]
    X = df[feat_cols].copy()

    y = df["Interaction Type"].copy()
    le = LabelEncoder()
    y_enc = le.fit_transform(y)

    pairs = df["Drug Pair"].astype(str).values
    strains = df["Strain"].astype(str).values
    
    # ==========================
    # 4) Make 5 brute-force outer CV2 folds with fixed min/max bands
    # ==========================
    bands = [
        (0.16, 0.20),
        (0.18, 0.22),
        (0.20, 0.24),
        (0.22, 0.26),
        (0.24, 0.28),
    ]

    cv2_splits = []
    for k, (mn, mx) in enumerate(bands, 1):
        print(f"\n=== Brute-force CV2 fold {k} | target={mn:.2f}-{mx:.2f} ===")
        tr_idx, te_idx, info = brute_force_cv2_split(
            df, "Strain", "Drug Pair", mn, mx, lambda_penalty=1.0, verbose=True
        )
        cv2_splits.append((tr_idx, te_idx, info))

        with open(out_dir / f"cv2_info_fold{k}.json", "w") as f:
            json.dump(info, f, indent=2, default=lambda x: list(x))

    # ==========================
    # 5) Nested CV and evaluation
    # ==========================
    class SilentLogger:
        def info(self, msg):
            pass

        def warning(self, msg):
            pass

    lgb.register_logger(SilentLogger())

    rng = np.random.default_rng(42)

    fold_results = []
    cm_total = None

    synergy_code = le.transform(["synergy"])[0]
    ant_code = le.transform(["antagonism"])[0]

    # loop over the 5 folds of outer CV (CV2)
    for fold_idx, (tr_idx, te_idx, info) in enumerate(cv2_splits, 1):
        print("\n" + "#" * 72)
        print(f"########## OUTER FOLD {fold_idx}/5 ##########")
        print("#" * 72)

        X_tr = X.iloc[tr_idx].reset_index(drop=True)
        X_te = X.iloc[te_idx].reset_index(drop=True)
        y_tr = y_enc[tr_idx]
        y_te = y_enc[te_idx]
        grp_tr = pairs[tr_idx]

        # The inner CV split, 3 folds, grouped by drug-pair
        def sample_one_params():
            max_depth = 3
            leaves_map = {3: [7, 9, 15]}
            return dict(
                boosting_type="gbdt",
                learning_rate=float(rng.choice([0.02, 0.03])),
                max_depth=max_depth,
                num_leaves=int(rng.choice(leaves_map[max_depth])),
                min_data_in_leaf=int(rng.choice([200, 300])),
                feature_fraction=float(rng.choice([0.30, 0.40, 0.50])),
                bagging_fraction=float(rng.choice([0.60, 0.70, 0.80])),
                bagging_freq=1,
                lambda_l2=float(10 ** rng.uniform(1.4, 1.9)),
                lambda_l1=float(rng.choice([0.0, 0.1, 0.5])),
                max_bin=int(rng.choice([63, 127])),
                min_gain_to_split=float(rng.choice([0.05, 0.10, 0.20])),
            )

        param_samples = [sample_one_params() for _ in range(32)]

        try:
            inner_cv = StratifiedGroupKFold(n_splits=3, shuffle=True, random_state=111)

            def inner_splitter():
                return inner_cv.split(X_tr, y_tr, groups=grp_tr)

        except Exception:
            inner_cv = GroupKFold(n_splits=3)

            def inner_splitter():
                return inner_cv.split(X_tr, y_tr, groups=grp_tr)

        # inner-CV hyperparameters scores and feature selection on INNER-TRAIN-ONLY
        def cv_acc_for_params(params):
            """
            Perform a full inner cross‑validation loop for a given hyperparameter
            configuration.

            For each inner fold:
            - Fit the feature selector only on the inner‑train split.
            - Select features for that fold.
            - Train a LightGBM model with the provided hyperparameters.
            - Evaluate accuracy on the inner‑validation split.

            Returns the mean validation accuracy across inner folds, used for
            comparing and ranking hyperparameter configurations in the nested CV.

            It is trying to answer: “If we used this hyperparameter configuration, 
            how well would the pipeline generalize?”
            """
            accs = []
            for tr_f, val_f in inner_splitter():
                Xf_tr = X_tr.iloc[tr_f].reset_index(drop=True)
                Xf_val = X_tr.iloc[val_f].reset_index(drop=True)
                yf_tr = y_tr[tr_f]
                yf_val = y_tr[val_f]

                selected_inner = select_features_lgbm(
                    X_train=Xf_tr,
                    y_train=yf_tr,
                    feat_cols=feat_cols,
                    corr_min=corr_min,
                    keep_top_frac=keep_top_frac,
                )

                Xf_tr_sel = Xf_tr[selected_inner]
                Xf_val_sel = Xf_val[selected_inner]

                m = lgb.LGBMClassifier(
                    objective="binary",
                    n_estimators=4000,
                    random_state=777,
                    n_jobs=4,
                    **params,
                )
                m.fit(
                    Xf_tr_sel,
                    yf_tr,
                    eval_set=[(Xf_val_sel, yf_val)],
                    eval_metric="binary_logloss",
                    callbacks=[lgb.early_stopping(100, False), lgb.log_evaluation(0)],
                )
                pred = m.predict(Xf_val_sel)
                accs.append(accuracy_score(yf_val, pred))
            return float(np.mean(accs))

        print(f"\n--- Inner CV search ({len(param_samples)} configs) ---")
        scores = [(cv_acc_for_params(ps), ps) for ps in param_samples]
        scores.sort(reverse=True, key=lambda t: t[0])
        best_acc, best_params = scores[0]
        print(f"Best ACC: {best_acc:.3f}")
        print("Best params:", best_params)

        # feature selection on FULL outer-train only
        selected_outer = select_features_lgbm(
            X_train=X_tr,
            y_train=y_tr,
            feat_cols=feat_cols,
            corr_min=corr_min,
            keep_top_frac=keep_top_frac,
        )

        X_tr_sel = X_tr[selected_outer]
        X_te_sel = X_te[selected_outer]

        # final refit on full outer-train 
        m_final = lgb.LGBMClassifier(
            objective="binary",
            n_estimators=4000,
            random_state=777,
            n_jobs=4,
            **best_params,
        )
        m_final.fit(X_tr_sel, y_tr)

        pos_idx = np.flatnonzero(m_final.classes_ == synergy_code)[0]

        # final evaluation on untouched outer-test
        p_te = m_final.predict_proba(X_te_sel)[:, pos_idx]
        y_pred = (p_te >= 0.5).astype(int)
        y_te_bin = (y_te == synergy_code).astype(int)

        accuracy_test = accuracy_score(y_te, y_pred)
        f1_macro_test = f1_score(y_te, y_pred, average="macro")
        f1_weighted_test = f1_score(y_te, y_pred, average="weighted")
        roc_auc_test = roc_auc_score(y_te_bin, p_te)

        print(f"\n=== OUTER FOLD {fold_idx} RESULTS ===")
        print(f"AUC      : {roc_auc_test:.3f}")
        print(f"Acc      : {accuracy_test:.3f}")
        print(f"F1-macro : {f1_macro_test:.3f}")
        print(f"F1-w     : {f1_weighted_test:.3f}")
        print("\nReport:\n", classification_report(y_te, y_pred, target_names=le.classes_))

        prec, rec, f1s, _ = precision_recall_fscore_support(
            y_te, y_pred, labels=[ant_code, synergy_code]
        )
        precision_antag, precision_syn = prec
        recall_antag, recall_syn = rec
        f1_antag, f1_syn = f1s

        order_idx = le.transform(["antagonism", "synergy"])
        cm = confusion_matrix(y_te, y_pred, labels=order_idx)
        if cm_total is None:
            cm_total = cm.copy()
        else:
            cm_total += cm

        fold_results.append(
            dict(
                fold=fold_idx,
                roc_auc=roc_auc_test,
                accuracy=accuracy_test,
                f1_macro=f1_macro_test,
                f1_weighted=f1_weighted_test,
                precision_antag=precision_antag,
                recall_antag=recall_antag,
                f1_antag=f1_antag,
                precision_syn=precision_syn,
                recall_syn=recall_syn,
                f1_syn=f1_syn,
            )
        )

    # ==========================
    # 6) Summary across folds
    # ==========================
    
    print("\n" + "=" * 72)
    print("===  Summary over 5 CV2 outer folds ===")
    for metric in ["roc_auc", "accuracy", "f1_macro", "f1_weighted"]:
        vals = [fr[metric] for fr in fold_results]
        print(f"{metric}_mean={np.mean(vals):.4f}  {metric}_std={np.std(vals):.4f}")

    pd.DataFrame(fold_results).to_csv(out_dir / "metrics_per_fold.csv", index=False)

    # ==========================
    # 7) Save aggregated confusion matrix
    # ==========================
    if cm_total is not None:
        order = ["antagonism", "synergy"]
        fig, ax = plt.subplots(figsize=(6, 5))
        disp = ConfusionMatrixDisplay(confusion_matrix=cm_total, display_labels=order)
        disp.plot(cmap="Blues", ax=ax, values_format="d")
        ax.set_title("Aggregated Confusion Matrix (5-fold CV2)", fontsize=13)
        plt.tight_layout()
        plt.savefig(out_dir / "confusion_matrix_cv2_allfolds.png", dpi=150)
        plt.close()

    print("\n=== EXP06c DONE ===\n")


if __name__ == "__main__":
    main()

